### ISSUE TITLE
The compiler and the pattern weavers are built for net472 and net10.0 instead of netstandard2.0

### ISSUE THREAD

**Issue by gfraiteur** [postsharp/PostSharp.Public#142]
## What changes

Until 2026.0, the compiler assemblies `PostSharp.Compiler.Common`, `PostSharp.Compiler.Engine` and `PostSharp.Compiler.Hosting` had a `netstandard2.0` build. The .NET compiler host ran that build, and the .NET Framework compiler host ran a separate `net472` build. The weavers of the pattern libraries had only a `netstandard2.0` build, which both hosts loaded from the `tools` directory of the package.

From 2027.0, these assemblies are built for `net472` and `net10.0`, the runtimes of the two compiler hosts. They have no `netstandard2.0` build.

This affects the following:

- **Weavers and add-ins.** A package now contains one build of its weaver for each runtime, in `tools/net472` and `tools/net10.0`. The compiler first looks for a plug-in in the subdirectory named after its own runtime. It then looks in the directory itself, as before. When a plug-in exists only for the other runtime, the build fails with the new error PS0283, which names the file that was found and the runtime it was built for.
- **The `PostSharp.Compiler.Engine` and `PostSharp.Compiler.Common` packages.** These packages contain reference assemblies for building an add-in. They move from `lib/netstandard2.0` to `lib/net472` and `lib/net10.0`. A project that targets `netstandard2.0` can no longer reference them.

The runtime library `PostSharp.dll` in `PostSharp.Redist`, and the runtime libraries of the pattern libraries, keep their `netstandard2.0` build. User projects are not affected.

## Why

A `netstandard2.0` build is compiled against the `netstandard2.0` build of its dependencies, but on .NET it runs against their `net10.0` build. Usually the two builds have the same API, and this works. It fails for a type that derives from a C# record of a dependency. The `net10.0` build of the base record declares its clone method with a covariant return type. The derived record, compiled for `netstandard2.0`, does not implement that method, and the type fails to load with a `TypeLoadException`.

The compiler stores its configuration files as records that derive from a record of the licensing and configuration services. A `netstandard2.0` build of the compiler cannot declare such a type.

## What to do

Nothing, if you use the pattern libraries: use the same version of all PostSharp packages.

If you maintain an add-in built with the `PostSharp.Compiler.Engine` package:

1. Build the add-in for `net472` and `net10.0` instead of `netstandard2.0`.
2. Package the two builds in `tools/net472` and `tools/net10.0`.

An add-in placed directly in the `tools` directory is still loaded, but it was built against the `netstandard2.0` compiler assemblies and may fail to load on .NET for the reason given above.

-- Claude for Gael
